### Get all blogs
GET localhost:3003/api/blogs

### Create a blog
POST localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test",
  "author": "Peler",
  "url": "test undefined",
  "likes": 10
}